from datetime import timedelta
from typing import TypeVar, Generic

T = TypeVar("T")

class FixedMapping(Generic[T]):
    def __init__(self, capacity: int, period: timedelta) -> None: ...
    def tokens(key: T) -> int: ...
    def next_reset(key: T) -> timedelta: ...
    def retry_after(key: T) -> timedelta | None: ...
    def can_trigger(key: T) -> bool: ...
    def trigger(key: T) -> timedelta | None: ...
    def reset(key: T) -> None: ...
    def start(cycle_period: timedelta | None = None) -> None: ...

class DynamicMapping(Generic[T]):
    def __init__(self, max_period: timedelta) -> None: ...
    def tokens(key: T, capacity: int, duration: timedelta) -> int: ...
    def next_reset(key: T, capacity: int, duration: timedelta) -> timedelta: ...
    def retry_after(key: T, capacity: int, duration: timedelta) -> timedelta | None: ...
    def can_trigger(key: T, capacity: int, duration: timedelta) -> bool: ...
    def trigger(key: T, capacity: int, duration: timedelta) -> timedelta | None: ...
    def reset(key: T, capacity: int, duration: timedelta) -> None: ...
    def start() -> None: ...

class JumpingWindow:
    def __init__(self, capacity: int, period: timedelta) -> None: ...
    def token(self) -> int: ...
    def next_reset(self) -> timedelta: ...
    def retry_after(self) -> timedelta | None: ...
    def can_trigger(self) -> bool: ...
    def trigger(self) -> timedelta | None: ...
    def reset(self) -> None: ...
