from typing import TypeVar, Generic

T = TypeVar("T")

class FixedMapping(Generic[T]):
    def __init__(self, capacity: int, period: float) -> None: ...
    def tokens(key: T) -> int: ...
    def next_reset(key: T) -> float: ...
    def retry_after(key: T) -> float | None: ...
    def can_trigger(key: T) -> bool: ...
    def trigger(key: T) -> float | None: ...
    def reset(key: T) -> None: ...
